development:
  host: localhost
  database: ask_app_development

test:
  host: localhost
  database: ask_app_test

# set these environment variables on your prod server
production:
  host: localhost
  database: ask_app_production
